### ISSUE TITLE
How to remove listener?

### ISSUE THREAD

**Issue by jcyh0120** [A-312/serverline#26]
I want to use "serverline" with other cli lib. Therefore I have to switch the controls.
When using `myRL.close()` I want to remove all the listeners but it is wrap in `EventEmitter`.

How can I remove the listeners?

**Comment by A-312** [comment]
Actually, we can't reload the stdout interface like before serverline loading. [close](https://nodejs.org/api/readline.html#readline_rl_close) only call readline.close(), it can't restore the state before serverline loading.

You have to revert this GLOBAL changes : (on `process.stdout`/`stderror` and `console.Console`)

https://github.com/A-312/serverline/blob/981f35671fbb69eafc0a397ba7e8361d62c0dcfa/bin/index.js#L228-L255

**Comment by jcyh0120** [comment]
Thanks for explain. I want to use serverline with Inquirer.js

Here's the use case:
1. inquirier ask questions
2. user answer then enter serverline console
3. user type \q and back to inquirier

Is it possible to use serverline in this use case?

I am trying to revert the consoleOverwrite by calling consoleReOverwrite when rl.close.
Then I re-call the sample code again and I am able to input any text to serverline again.
```
let writeClone = process.stdout._write
let writeErrorClone = process.stderr._write

function consoleReOverwrite (options) {

  process.stdout._write = writeClone
  process.stderr._write = writeErrorClone

  const Console = console.Console
  const consoleOptions = Object.assign({}, {
    stdout: process.stdout,
    stderr: process.stderr
  }, options)
  console = new Console(consoleOptions) // eslint-disable-line no-global-assign 
  console.Console = Console
}
```

**Comment by A-312** [comment]
I don't have much time to make a full fix for `Inquirer` but I can explain you what is wrong with the [example code](https://github.com/A-312/serverline#example-serverbinindexjs) try : 

This code will work fine : 

```js
function exempleHowToNotBreakServerline() {
  setInterval(() => console.log('test'), 400);
}
exempleHowToNotBreakServerline()
```

This code will not work fine because you use `process.stdout` : 

```js
function exempleHowToBreakServerline() {
  setInterval(() => process.stdout.write('test\n'), 400);
}
exempleHowToBreakServerline()
```

You can fix the precedent code with : 
```js
function exempleHowToBreakServerline_Fix() {
  setInterval(() => myRL.getCollection().stdout.write('test\n'), 400);
}
exempleHowToBreakServerline_Fix()
```

I will commit `getCollection()` in the next version (give me one hours).

--------

You have to change the behavior of Inquirer, Inquirer should use stdout of serverline not the default one. (Ask a setting to use your own stdout).

**Comment by A-312** [comment]
@jcyh0120 1.5.0 is published, I think, it is the best thing I can do, now it is on Inquirer side to allow custom stdout.

**Comment by jcyh0120** [comment]
@A-312 Thanks!!! I will try to use the exposed collection.
