### ISSUE TITLE
Line refresh not working?

### ISSUE THREAD

**Issue by wizzfizz94** [A-312/serverline#30]
Hi. I'm trying to incorporate this neat package into a rather large system (includes a web server and various network connections). It's mostly working but the console line is not refreshing when new stdout is logged. Instead it is cleared but the entire line is still being passed to the `line` callback. See gif below for example:

![Peek 2021-07-09 15-10](https://user-images.githubusercontent.com/13703641/125038316-dadd9300-e0c7-11eb-9d0a-52b9021a94be.gif)

I've tried to fix this by placing the init call at the very end of my application initialization (and at the very start!) to make sure the global console overide works. Init looks like this:
```js
myRL.init();
myRL.setPrompt("> ");
```

I've tried disabling all alterations on the global `console` object, any calls to `process.stdin` or `process.stdout`, removing all debug calls and imports. I don't know if promises and sync/await will effect this module but that could be the potential problem. Any ideas what could be causing this issue? I can confirm the example script given works on my machine.

**Comment by Nerdsie** [comment]
Just ran into this myself, for me the issue is running via `nodemon`, I solved the problem by adding using the `-I` flag, so something like `nodemon -I script.js`

**Comment by wizzfizz94** [comment]
@Nerdsie right on the money! Adding that `-I` flag fixed the issue. Need to remember issues with the console often involve nodemon. Thanks for your help.
